# light-conf, prop file location, if not empty this file will be replaced with this disk file, like "file:/data/webapps/light-conf.properties" or "light-conf02.properties"
light.conf.prop.file.location=
#netty
netty.server.port=9998
